# Generated by Django 3.2.20 on 2023-09-29 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_xcdsfs'),
        ('users', '0002_auto_20230929_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rel_xcdsfs_n_n',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_rel_xcdsfs_n_n', to='home.Xcdsfs'),
        ),
    ]
